### ISSUE TITLE
l2munger may not understand 2021 Level II data

### ISSUE THREAD

**Issue by akrherz** [akrherz/l2munger#4]
Running `l2munger` against a current Level II file yields

```
$ ./l2munger KDMX 2021/03/24 17:43:00 1 KDMX20210324_174300
destination file = KDMX20210324_174300
ProcessFileHeader:
*** fread failed!
```

**Comment by jthielen** [comment]
I've been able to run it successfully on 2021 files going back a few days; could it possibly be related to this: https://github.com/Unidata/MetPy/issues/1470?

**Comment by akrherz** [comment]
Thanks, my example wasn't obvious, but was attempting to do current FWS data.

**Comment by akrherz** [comment]
Interestingly, this DMX example volume scan is not found on AWS.  Perhaps I got extremely unlucky and picked a time with corrupted level II files?  I can't reproduce this bug now...

**Comment by akrherz** [comment]
I don't think this is valid anymore.
